Document: qmapboxgl
Title: Debian qmapboxgl Manual
Author: <insert document author here>
Abstract: This manual describes what qmapboxgl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qmapboxgl/qmapboxgl.sgml.gz

Format: postscript
Files: /usr/share/doc/qmapboxgl/qmapboxgl.ps.gz

Format: text
Files: /usr/share/doc/qmapboxgl/qmapboxgl.text.gz

Format: HTML
Index: /usr/share/doc/qmapboxgl/html/index.html
Files: /usr/share/doc/qmapboxgl/html/*.html
